config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get "search"
    end
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  mount_uploader :image, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  validates :text, presence: true

  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  def self.search(search)
    if search
      Post.where('text LIKE(?)', "%#{search}%")
    else
      Post.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}"
    # respond_to do |format|
    #   format.html { redirect_to "/posts/#{@comment.post.id}" }
    # end
  end

  def destroy
    comment = Comment.destroy(params[:id])
    redirect_to "/posts/#{comment.post.id}"
  end
  

  private

  def comment_params
    params.require(:comment).permit(:text, :image).merge(user_id: current_user.id, post_id: params[:post_id])
  end
  
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]
  def index
    @posts = Post.includes(:user).order("created_at DESC")
  end
  def new
    @post = Post.new
  end
  def create
    Post.create(post_params)
  end
  def destroy
    post = Post.find(params[:id])
    post.destroy
  end
  def edit
    
  end
  def update
    post = Post.find(params[:id])
    post.update(post_params)
  end
  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order("created_at ASC")
    @like = Like.new
  end
  def search
    @posts = Post.search(params[:keyword])
  end
  
  private

  def post_params
    params.require(:post).permit(:image, :text).merge(user_id: current_user.id)
  end
  def set_post
    @post = Post.find(params[:id])
  end
  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @user = User.find(params[:id])
    @name = user.name
    @posts = user.posts.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{href: "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css", rel: "stylesheet", id: "bootstrap-css"}/
    %title Steady
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
    
  %body.container.wrapper

    %header
      %h3.display-4
        STEADY
      = render 'layouts/notifications'
      - if user_signed_in?
        %p
          username: #{current_user.name}
          %br/
          = link_to root_path do
            ホーム
          = link_to "/users/#{current_user.id}" do
            マイページ
          = link_to destroy_user_session_path, method: :delete do
            ログアウト
          = link_to new_post_path do
            投稿する
      - else
        %p
          = link_to root_path do
            ホーム
          = link_to new_user_session_path do
            ログイン
          = link_to new_user_registration_path do
            新規登録
      = yield
    %footer
      %p
        Copyright STEADY 2020.

app/views/posts/_form.html.haml
-# .form-group
-#   = label_tag("name", "Name")
-#   = f.text_field("name", {class: "form-control"})
.form-group
  = label_tag("text", "Text")
  = f.text_area("text", {rows: 5, class: "form-control"})
.form-group
  = label_tag("image", "Image URL")
  = f.file_field("image", {class: "form-control-file"})
= submit_tag("SEND", {class: "btn btn-primary"})

app/views/posts/create.html.haml
%h1.display-4.text-success
  Good！Tweet has been saved!
%p
  投稿できました！
%p
  = link_to "/" do
    &lt;&lt;トップページに戻る

app/views/posts/destroy.html.haml
%h1.display-4.text-success
  Good！Tweet has been deleted!
%p
  削除しました！
%p
  = link_to "/" do
    &lt;&lt;トップページに戻る

app/views/posts/edit.html.haml
%h1.display-4.text-primary
  Edit Tweet
%p
  編集する内容を入力してください
= form_with(model: @post, local: true) do |f|
  = render partial: "form", locals: { f: f }
%p
  = link_to "/" do
    &lt;&lt;トップページに戻る

app/views/posts/index.html.haml
%h1.display-4.text-primary
  Tweet List
%p
  現在、登録されているデータの一覧です。
%nav.navbar.navbar-light.bg-light
  = form_with(url: search_posts_path, local: true, method: :get, class: "form-inline") do |f|
    = f.text_field("keyword", {placeholder: "Keyword", class: "form-control mr-sm-2"})
    = submit_tag("Search", {class: "btn btn-outline-primary my-2 my-sm-0"})
%table.table
  %tr
    %th
      ID
    %th
      Name
    %th
      Text
    %th
      Image
    %th
      Created_at
    %th{colspan: "2"}
  - @posts.each do |post|
    %tr
      %td{width: "35px"}
        = post.id
      %td{width: "100px"}
        = link_to "/users/#{post.user.id}" do
          = post.user.name
        %br/
        = icon('far', 'heart', class: "text-danger")
        #{post.liked_users.count}
      %td{width: "200px"}
        = link_to "/posts/#{post.id}" do
          = post.text
      %td
        = image_tag post.image_url(:thumb) if post.image.present?
      %td
        = post.created_at.to_s(:datetime)
      - if user_signed_in? && current_user.id == post.user_id
        %td{width: "80px"}
          = link_to edit_post_path(post.id) do
            編集
        %td{witdh: "80px"}
          = link_to post_path(post.id), method: :delete, data: {confirm: "削除しますか？"} do
            削除
%p
  = link_to "#" do
    ※ページの上部へ戻る &gt;&gt;
-# :javascript
-#   function delData(num) {
-#     if(confirm('このデータを削除しますか？')) {
-#       document.location = "/posts/" + num;
-#     }
-#   }

app/views/posts/new.html.haml
%h1.display-4.text-primary
  New Tweet
%p
  登録するTweetを入力してください
= form_with(model: @post, local: true) do |f|
  = render partial: "form", locals: { f: f }
%p
  = link_to "/" do
    &lt;&lt;トップページに戻る

app/views/posts/search.html.haml
%h1.display-4.text-primary
  Search Result
%p
  検索結果の一覧です。
%nav.navbar.navbar-light.bg-light
  = form_with(url: search_posts_path, local: true, method: :get, class: "form-inline") do |f|
    = f.text_field("keyword", {placeholder: "Keyword", class: "form-control mr-sm-2"})
    = submit_tag("Search", {class: "btn btn-outline-primary my-2 my-sm-0"})
%table.table
  %tr
    %th
      ID
    %th
      Name
    %th
      Text
    %th
      Image
    %th
      Created_at
    %th{colspan: "2"}
  - @posts.each do |post|
    %tr
      %td{width: "35px"}
        = post.id
      %td{width: "100px"}
        = link_to "/users/#{post.user.id}" do
          = post.user.name
      %td{width: "200px"}
        = link_to "/posts/#{post.id}" do
          = post.text
      %td
        = image_tag post.image_url(:thumb) if post.image.present?
      %td
        = post.created_at.to_s(:datetime)
      - if user_signed_in? && current_user.id == post.user_id
        %td{width: "80px"}
          = link_to edit_post_path(post.id) do
            編集
        %td{witdh: "80px"}
          = link_to post_path(post.id), method: :delete, data: {confirm: "削除しますか？"} do
            削除
%p
  = link_to "#" do
    ※ページの上部へ戻る &gt;&gt;
-# :javascript
-#   function delData(num) {
-#     if(confirm('このデータを削除しますか？')) {
-#       document.location = "/posts/" + num;
-#     }
-#   }

app/views/posts/show.html.haml
%h1.display-4.text-primary
  Tweet details
%p
  このツイートの詳細内容です。

%h3
  いいね件数: #{@post.likes.count}
- if current_user.already_liked?(@post)
  = button_to 'いいねを取り消す', post_like_path(@post), method: :delete, class: "btn btn-outline-primary"
- else
  = button_to 'いいね', post_likes_path(@post),class: "btn btn-outline-primary"
%h2 いいねしたユーザー
- @post.liked_users.each do |user|
  %li= user.name

%table.table
  %tr
    %th
      ID
    %th
      Name
    %th
      Text
    %th
      Image
    %th
      Created_at
    %th{colspan: "2"}
  %tr
    %td{width: "35px"}
      = @post.id
    %td{width: "100px"}
      = @post.user.name
    %td{width: "200px"}
      = @post.text
    %td
      = image_tag @post.image_url(:thumb) if @post.image.present?
    %td
      = @post.created_at.to_s(:datetime)
    - if user_signed_in? && current_user.id == @post.user_id
      %td{width: "80px"}
        = link_to edit_post_path(@post.id) do
          編集
      %td{witdh: "80px"}
        = link_to post_path(@post.id), method: :delete, data: {confirm: "削除しますか？"} do
          削除
- if current_user
  %p
    コメントを入力してください
  = form_with(model: [@post, @comment], local: true, id: "new_comment") do |f|
    .form-group
      = label_tag("text", "Comment")
      = f.text_area("text", {rows: 2, class: "form-control textbox"})
    .form-group
      = label_tag("image", "Image URL")
      = f.file_field("image", {class: "form-control-file imagebox"})
    = submit_tag("SEND", {class: "btn btn-primary form__submit"})
- else
  %p
    >>コメントする場合はログインしてください
%p
  コメント一覧
- if @comments
  %table.table
    %tr
      %th
        ID
      %th
        Name
      %th
        Text
      %th
        Image
      %th
        Created_at
      %th{colspan: "2"}
    - @comments.each do |comment|
      %tr
        %td{width: "35px"}
          = comment.id
        %td{width: "100px"}
          = link_to "/users/#{comment.user.id}" do
            = comment.user.name
        %td{width: "200px"}
          = comment.text
        %td
          = image_tag comment.image_url(:thumb) if comment.image.present?
        %td
          = comment.created_at.to_s(:datetime)
        - if user_signed_in? && current_user.id == comment.user_id
          -# %td{width: "80px"}
          -#   = link_to edit_post_path(comment.id) do
          -#     編集
          %td{witdh: "80px"}
            = link_to [@post, comment], method: :delete, data: {confirm: "削除しますか？"} do
              削除


%p
  = link_to "#" do
    ※ページの上部へ戻る &gt;&gt;
-# %p
-#   = link_to "/posts/new" do
-#     ※新しいTweetを入力 &gt;&gt;

app/views/posts/update.html.haml
%h1.display-4.text-success
  Good！Tweet has been updated!
%p
  更新しました！
%p
  = link_to "/" do
    &lt;&lt;トップページに戻る

app/views/users/show.html.haml
%h1.display-4.text-primary
  #{@name}'s Tweets
%p
  #{@name}さんの投稿一覧です。
%table.table
  %tr
    %th
      ID
    -# %th
    -#   Name
    %th
      Text
    %th
      Image
    %th
      Created_at
    %th{colspan: "2"}
  - @posts.each do |post|
    %tr
      %td{width: "35px"}
        = post.id
      -# %td{width: "100px"}
      -#   = post.user.name
      %td{width: "200px"}
        = link_to "/posts/#{post.id}" do
          = post.text
      %td
        = image_tag post.image_url(:thumb) if post.image.present?
      %td
        = post.created_at.to_s(:datetime)
      - if user_signed_in? && current_user.id == post.user_id
        %td{width: "80px"}
          = link_to edit_post_path(post.id) do
            編集
        %td{witdh: "80px"}
          = link_to post_path(post.id), method: :delete, data: {confirm: "削除しますか？"} do
            削除

%h3
  いいねしている投稿
%table.table
  %tr
    %th
      ID
    %th
      Name
    %th
      Text
    %th
      Image
    %th
      Created_at
    %th{colspan: "2"}
  - @user.liked_posts.each do |post|
    %tr
      %td{width: "35px"}
        = post.id
      %td{width: "100px"}
        = link_to "/users/#{post.user.id}" do
          = post.user.name
        %br/
        = icon('far', 'heart', class: "text-danger")
        #{post.liked_users.count}
      %td{width: "200px"}
        = link_to "/posts/#{post.id}" do
          = post.text
      %td
        = image_tag post.image_url(:thumb) if post.image.present?
      %td
        = post.created_at.to_s(:datetime)

%p
  = link_to "#" do
    ※ページの上部へ戻る &gt;&gt;
-# :javascript
-#   function delData(num) {
-#     if(confirm('このデータを削除しますか？')) {
-#       document.location = "/posts/" + num;
-#     }
-#   }